#!/bin/sh
#
# A helper devscript to recreate CDS demo site.  Assumes an
# already running Invenio instance on the box, and certain sudo
# rights.  For more information, see
# <https://github.com/jerome.caffaro/cds-devscripts>.
#
# Cloned from <https://github.com/tiborsimko/inspire-devscripts>
#
# Tibor Simko <tibor.simko@cern.ch>
#
# Copyright (C) 2011, 2012, 2013 CERN.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.

# config section:
CFG_INVENIO_SRCDIR=${CFG_INVENIO_SRCDIR:=~/private/src/invenio}
CFG_CDS_SRCDIR=${CFG_CDS_SRCDIR:=~/private/src/invenio-cern}
CFG_CDS_BIBTASK_USER=${CFG_CDS_BIBTASK_USER:=admin}
CFG_INVENIO_PREFIX=${CFG_INVENIO_PREFIX:=/opt/invenio}
CFG_INVENIO_HOSTNAME=${CFG_INVENIO_HOSTNAME:=pccis06}
CFG_INVENIO_DOMAINNAME=${CFG_INVENIO_DOMAINNAME:=cern.ch}
CFG_INVENIO_USER=${CFG_INVENIO_USER:=www-data}
CFG_INVENIO_ADMIN=${CFG_INVENIO_ADMIN:=jerome.caffaro@cern.ch}
CFG_INVENIO_DATABASE_NAME=${CFG_INVENIO_DATABASE_NAME:=invenio}
CFG_INVENIO_DATABASE_USER=${CFG_INVENIO_DATABASE_USER:=invenio}
CFG_INVENIO_PORT_HTTP=${CFG_INVENIO_PORT_HTTP:=80}
CFG_INVENIO_PORT_HTTPS=${CFG_INVENIO_PORT_HTTPS:=443}

# sanity check:
if [ "$1" != "--yes-i-know" ]; then
    echo "[ERROR] You did not use --yes-i-know.  Not going to recreate CDS demo site."
    exit
fi

# quit on errors and potentially unbound symbols:
set -o errexit
set -o nounset

# sanity check: hostname
if [ "`hostname`" != "$CFG_INVENIO_HOSTNAME" ]; then
    echo "[ERROR] This hostname is not whitelisted for recreating the demo site."
    exit
fi

# give user a chance to quit:
echo "[INFO] GOING TO RECREATE YOUR CDS DEMO SITE IN 5 SECONDS!"
echo "[INFO] THIS IS YOUR LAST CHANCE TO INTERRUPT BY PRESSING Ctrl-C!"
for i in 0 1 2 3 4; do
    echo -n "."
    sleep 1
done
echo


# install Invenio sources:
cd $CFG_INVENIO_SRCDIR
make -s && sudo -u $CFG_INVENIO_USER make -s install
#sudo -u $CFG_INVENIO_USER make -s install-jquery-plugins
#sudo -u $CFG_INVENIO_USER make -s install-mathjax-plugin
#sudo -u $CFG_INVENIO_USER make -s install-ckeditor-plugin
#sudo -u $CFG_INVENIO_USER make -s install-pdfa-helper-files
#sudo -u $CFG_INVENIO_USER make -s install-solrutils

# set up invenio-local.conf:
siteurl=${CFG_INVENIO_HOSTNAME}
if [ "${CFG_INVENIO_DOMAINNAME}" = "localhost" ]; then
    siteurl="localhost"
else
    siteurl=${siteurl}.${CFG_INVENIO_DOMAINNAME}
fi
sitesecureurl=${siteurl}
if [ "${CFG_INVENIO_PORT_HTTP}" != "80" ]; then
    siteurl=${siteurl}:${CFG_INVENIO_PORT_HTTP}
fi
if [ "${CFG_INVENIO_PORT_HTTPS}" != "443" ]; then
    sitesecureurl=${sitesecureurl}:${CFG_INVENIO_PORT_HTTPS}
fi
echo "[Invenio]
CFG_SITE_URL = http://${siteurl}
CFG_SITE_SECURE_URL = https://${sitesecureurl}
CFG_DATABASE_NAME = ${CFG_INVENIO_DATABASE_NAME}
CFG_DATABASE_USER = ${CFG_INVENIO_DATABASE_USER}
CFG_SITE_ADMIN_EMAIL = ${CFG_INVENIO_ADMIN}
CFG_SITE_SUPPORT_EMAIL = ${CFG_INVENIO_ADMIN}
CFG_WEBALERT_ALERT_ENGINE_EMAIL = ${CFG_INVENIO_ADMIN}
CFG_WEBCOMMENT_ALERT_ENGINE_EMAIL = ${CFG_INVENIO_ADMIN}
CFG_WEBCOMMENT_DEFAULT_MODERATOR = ${CFG_INVENIO_ADMIN}
CFG_BIBAUTHORID_AUTHOR_TICKET_ADMIN_EMAIL = ${CFG_INVENIO_ADMIN}" | \
    sudo -u $CFG_INVENIO_USER tee $CFG_INVENIO_PREFIX/etc/invenio-local.conf

# install Atlantis demo site without records:
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/inveniocfg --update-all
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/inveniocfg --drop-demo-site --yes-i-know
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/inveniocfg --create-demo-site --yes-i-know

# prepare symbolic links expected by some scripts
if ! [ -L /opt/cdsweb ]; then
    sudo ln -fs $CFG_INVENIO_PREFIX /opt/cdsweb
fi
if ! [ -L /soft ]; then
    sudo ln -fs /opt /soft
fi
if ! [ -L /soft/cdsweb ]; then
    sudo ln -fs $CFG_INVENIO_PREFIX /soft/cdsweb
fi

# install CDS sources:
cd $CFG_CDS_SRCDIR
make -s
sudo -u $CFG_INVENIO_USER make -s install-yes-i-know

# make sure BibTasks can run:
sudo -u $CFG_INVENIO_USER  sh -c "echo -e '\nCFG_CERN_SITE = 1' >> $CFG_INVENIO_PREFIX/lib/python/invenio/config.py"

# install CDS DB changes:
sudo -u $CFG_INVENIO_USER CFG_CDS_BIBTASK_USER=$CFG_CDS_BIBTASK_USER make -s install-dbchanges

# create CDS-specific invenio-local.conf:
sudo -u $CFG_INVENIO_USER sh -c "sed -n '/END-customize-me/,\$p' $CFG_CDS_SRCDIR/conf/invenio-local.conf-example >> $CFG_INVENIO_PREFIX/etc/invenio-local.conf"
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/inveniocfg --update-all --yes-i-know
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/inveniocfg --reset-all --yes-i-know
# add legacy variables:
sudo -u $CFG_INVENIO_USER sh -c "cat $CFG_CDS_SRCDIR/conf/invenio-old-config-vars >> $CFG_INVENIO_PREFIX/lib/python/invenio/config.py"

# load CDS demo site:
echo "TRUNCATE schTASK" | $CFG_INVENIO_PREFIX/bin/dbexec
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/bibupload -i $CFG_CDS_SRCDIR/demo/cds-demobibdata.xml
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/bibupload 1
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/bibindex -u admin
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/bibindex 2
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/bibreformat -u admin -o HB
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/bibreformat 3
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/webcoll -u admin
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/webcoll 4
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/bibrank -u admin
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/bibrank 5

# restart Invenio WSGI app:
sudo -u $CFG_INVENIO_USER touch $CFG_INVENIO_PREFIX/var/www-wsgi/invenio.wsgi

echo "[INFO] Done."
