#!/bin/sh
#
# A helper devscript to recreate INSPIRE demo site.  Assumes an
# already running Invenio instance on the box, and certain sudo
# rights.  For more information, see
# <https://github.com/tiborsimko/inspire-devscripts>.
#
# Tibor Simko <tibor.simko@cern.ch>
#
# Copyright (C) 2011 CERN.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.

# config section:
CFG_INVENIO_SRCDIR=${CFG_INVENIO_SRCDIR:=~/private/src/invenio}
CFG_INSPIRE_SRCDIR=${CFG_INSPIRE_SRCDIR:=~/private/src/inspire}
CFG_INVENIO_PREFIX=${CFG_INVENIO_PREFIX:=/opt/invenio}
CFG_INVENIO_HOSTNAME=${CFG_INVENIO_HOSTNAME:=pcuds07}
CFG_INVENIO_DOMAINNAME=${CFG_INVENIO_DOMAINNAME:=cern.ch}
CFG_INVENIO_USER=${CFG_INVENIO_USER:=www-data}
CFG_INVENIO_ADMIN=${CFG_INVENIO_ADMIN:=tibor.simko@cern.ch}

# sanity check:
if [ "$1" != "--yes-i-know" ]; then
    echo "[ERROR] You did not use --yes-i-know.  Not going to recreate INSPIRE demo site."
    exit
fi

# quit on errors and potentially unbound symbols:
set -o errexit
set -o nounset

# sanity check: hostname
if [ "`hostname`" != "$CFG_INVENIO_HOSTNAME" ]; then
    echo "[ERROR] This hostname is not whitelisted for recreating the demo site."
    exit
fi

# give user a chance to quit:
echo "[INFO] GOING TO RECREATE YOUR INSPIRE DEMO SITE IN 5 SECONDS!"
echo "[INFO] THIS IS YOUR LAST CHANCE TO INTERRUPT BY PRESSING Ctrl-C!"
for i in 0 1 2 3 4; do
    echo -n "."
    sleep 1
done
echo

# install Invenio sources:
cd $CFG_INVENIO_SRCDIR
make -s && sudo -u $CFG_INVENIO_USER make -s install

# install Atlantis demo site without records:
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/inveniocfg --drop-demo-site \
                                                     --create-demo-site \
                                                     --yes-i-know

# install INSPIRE sources:
cd $CFG_INSPIRE_SRCDIR
make -s
sudo -u $CFG_INVENIO_USER make -s install

# install INSPIRE DB changes:
sudo -u $CFG_INVENIO_USER make -s install-dbchanges

# create INSPIRE-specific invenio-local.conf:
sudo -u $CFG_INVENIO_USER cp $CFG_INVENIO_PREFIX/etc/invenio-local.conf-example \
        $CFG_INVENIO_PREFIX/etc/invenio-local.conf
sudo -u $CFG_INVENIO_USER sed -i -e "s/^CFG_SITE_URL = .*$/CFG_SITE_URL = http:\/\/${CFG_INVENIO_HOSTNAME}.${CFG_INVENIO_DOMAINNAME}/" \
        $CFG_INVENIO_PREFIX/etc/invenio-local.conf
sudo -u $CFG_INVENIO_USER sed -i -e "s/^CFG_SITE_SECURE_URL = .*$/CFG_SITE_SECURE_URL = https:\/\/${CFG_INVENIO_HOSTNAME}.${CFG_INVENIO_DOMAINNAME}/" \
        $CFG_INVENIO_PREFIX/etc/invenio-local.conf
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/inveniocfg --update-all --reset-all

# load INSPIRE demo site:
echo "TRUNCATE schTASK" | $CFG_INVENIO_PREFIX/bin/dbexec
cd bibconvert
make get-small
make convert-small
sudo -u $CFG_INVENIO_USER make upload-small
make get-inst
make convert-inst
sudo -u $CFG_INVENIO_USER make upload-inst
cd ..
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/bibupload 1
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/bibupload 2
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/bibindex -u admin
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/bibindex 3
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/bibreformat -u admin -o HB
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/bibreformat 4
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/webcoll -u admin
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/webcoll 5
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/bibrank -u admin
sudo -u $CFG_INVENIO_USER $CFG_INVENIO_PREFIX/bin/bibrank 6

# restart Invenio WSGI app:
sudo -u $CFG_INVENIO_USER touch $CFG_INVENIO_PREFIX/var/www-wsgi/invenio.wsgi

echo "[INFO] Done."
