#+TITLE:     CDS Devscript
#+DATE:      2013-06-17 lun
#+DESCRIPTION: A collection of scripts useful for CDS development.
#+KEYWORDS: invenio, cds, development, scripts
#+LANGUAGE: en

* About cds-devscripts

=cds-devscripts= repository contains a collection of scripts
useful when hacking on the CDS instance of [[http://invenio-software.org/][Invenio]].  Since CDS
source code repository is a sort of overlay on top of Invenio source
code repository, see also accompanying =invenio-devscripts=.

* Contents

- cds-recreate-demo-site :: recreate CDS demo site

* Installation

See =invenio-devscripts= repository instructions; the same applies
here.  In addition to the configuration environment variables
mentioned there, you may also want to tweak:

| Variable                 | Documentation                    | Default value         |
| CFG_CDS_SRCDIR       | where are CDS sources?       | ~/private/src/invenio-cern     |
| CFG_CDS_BIBTASK_USER | submit initial bibtasks as whom? | admin                 |

* Usage

** cds-recreate-demo-site

Having a running Invenio installation, run this command to erase given
Invenio instance and reinstall new fresh CDS demo site.

For example, here are commands to run in order to set up a completely
new virtualenv environment called =cds-master= that will run
CDS demo site on top of Invenio =master= branch:

#+BEGIN_SRC sh
cd ~/private/src/invenio
git checkout master
mkvirtualenv --system-site-packages cds-master
invenio-initialise-virtualenv cds-master --yes-i-know
deactivate && workon cds-master
invenio-recreate-demo-site --yes-i-know
cds-recreate-demo-site --yes-i-know
#+END_SRC

* License

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, see [[http://www.gnu.org/licenses/]].

* See also

- [[http://invenio-software.org/][Invenio]]
- [[https://github.com/tiborsimko/invenio-devscripts][invenio-devscripts]]
