#+TITLE: INSPIRE Devscripts
#+AUTHOR: Tibor Simko
#+EMAIL: tibor.simko@cern.ch
#+DATE: <2012-12-06 Thu>
#+DESCRIPTION: A collection of scripts useful for INSPIRE development.
#+KEYWORDS: invenio, inspire, development, scripts
#+LANGUAGE: en

* About inspire-devscripts

=inspire-devscripts= repository contains a collection of scripts
useful when hacking on the INSPIRE instance of [[http://invenio-software.org/][Invenio]].  Since INSPIRE
source code repository is a sort of overlay on top of Invenio source
code repository, see also accompanying =invenio-devscripts=.

* Contents

- inspire-recreate-demo-site :: recreate INSPIRE demo site

* Installation

See =invenio-devscripts= repository instructions; the same applies
here.  In addition to the configuration environment variables
mentioned there, you may also want to tweak:

| Variable           | Documentation              | Default value         |
| CFG_INSPIRE_SRCDIR | where are INSPIRE sources? | ~/private/src/inspire |

* Usage

** inspire-recreate-demo-site

Having a running Invenio installation, run this command to erase given
Invenio instance and reinstall new fresh INSPIRE demo site.

For example, here are commands to run in order to set up a completely
new virtualenv environment called =inspire-maint-1.1= that will run
INSPIRE demo site on top of Invenio =maint-1.1= branch:

#+BEGIN_SRC sh
cd ~/private/src/invenio
git checkout maint-1.1
mkvirtualenv --system-site-packages inspire-maint-1.1
invenio-initialise-virtualenv inspire-maint-1.1 --yes-i-know
deactivate && workon inspire-maint-1.1
invenio-recreate-demo-site --yes-i-know
inspire-recreate-demo-site --yes-i-know
#+END_SRC

* License

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, see [[http://www.gnu.org/licenses/]].

* See also

- [[http://invenio-software.org/][Invenio]]
- [[https://github.com/tiborsimko/invenio-devscripts][invenio-devscripts]]
